//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTBL
    {
        public int AppointmentId { get; set; }
        public int AppointmentTypeId { get; set; }
        public string ConsumerId { get; set; }
        public string StatusCode { get; set; }
        public string ConsumerName { get; set; }
    }
}
